" Example .vimrc for use with Vim LSP

:filetype on
au FileType * setl fo-=cro

" Do not automatically paste text as if in insert mode.
:set t_BE=

" Configuration for Vim LSP
let g:system_vimlsp_file = expand('~/.vim/misc/sde/vim-lsp.vim')
let g:user_vimlsp_file = expand('~/.vimrc-vimlsp')
if filereadable(g:vimrc_lsp_file)
	:execute ':so' g:vimrc_lsp_file
	let g:lsp_log_verbose = 1
	let g:lsp_log_file = expand('~/.vim-lsp.log')
	if filereadable(g:vimrc_user_lsp_file)
		:execute ':so' g:vimrc_user_lsp_file
	endif
endif
